# Generated by Django 5.1.7 on 2025-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
