# Generated by Django 5.1.7 on 2025-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tool',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
