# Generated by Django 5.1.7 on 2025-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_tool_name_alter_tool_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildobject',
            name='current_budget',
            field=models.FloatField(default=50000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildobject',
            name='total_budget',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
