# Generated by Django 5.1.7 on 2025-05-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildobject_current_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildobject',
            name='current_budget',
        ),
    ]
