# Generated by Django 5.1.7 on 2025-05-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_buildobject_current_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildobject',
            name='current_budget',
            field=models.FloatField(default=0),
        ),
    ]
