# Generated by Django 5.1.7 on 2025-05-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_buildobject_current_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildBudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_budget', models.FloatField()),
                ('build_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_history', to='buildings.buildobject')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('build_object', 'date')},
            },
        ),
    ]
